blank_issues_enabled: false
contact_links:
  - name: ğŸ“˜ Documentation
    url: https://github.com/tursodatabase/turso-docs
    about: Can something be improved in our docs? Let us know, or open a Pull Request.
  - name: ğŸ’ Support
    url: https://tur.so/ghdiscord
    about: Get help and chat with us on Discord.
  - name: ğŸ’¡ Feedback & Feature Requests
    url: https://tur.so/ghdiscord
    about: Share your feedback, and request new features on Discord!
